## Write a Numpy program to compute the multiplication of two given matrixes

In [16]:
import numpy as np

mat1 = np.array([[1,2,3], [4,5,6], [6,7,8]])
mat2 = np.array([[1,2,3], [4,5,6], [6,7,8]])

In [17]:
mat1 * mat2

array([[ 1,  4,  9],
       [16, 25, 36],
       [36, 49, 64]])

## Write a NumPy program to compute the determinant of a given square array

In [18]:
mat3 = mat1 ** 2
mat3

array([[ 1,  4,  9],
       [16, 25, 36],
       [36, 49, 64]], dtype=int32)

In [19]:
np.linalg.det(mat3)

-120.00000000000018

## Write a NumPy program to compute the cross product of two given vectors

In [22]:
np.cross(mat1, mat3)

array([[  6,  -6,   2],
       [ 30, -48,  20],
       [ 56, -96,  42]])

In [23]:
np.cross(mat3, mat1)

array([[ -6,   6,  -2],
       [-30,  48, -20],
       [-56,  96, -42]])

## Write a NumPy program to compute the condition number of a given matrix

In [24]:
np.linalg.cond(mat1)

1.639046654704083e+17

## Write a NumPy program to compute the inverse of a given matrix

In [27]:
np.linalg.inv(mat1)

array([[ 1.7156570e+15, -4.2891425e+15,  2.5734855e+15],
       [-3.4313140e+15,  8.5782850e+15, -5.1469710e+15],
       [ 1.7156570e+15, -4.2891425e+15,  2.5734855e+15]])